### ISSUE TITLE
Nome oggetto flottante

### ISSUE THREAD

**Issue by robitex** [GuITeX/atkit#2]
Ciao,
Ho notato che nell'ultimo numero di Ars in alcuni articoli qualcuno ha definito un nuovo nome per oggetti flottanti "Codice" per riferire listati nelle caption.
Tuttavia, negli articoli successivi, dove doveva apparire "Figura numero" è continuato ad apparire "Codice numero".
Roberto

Ps. questo è un ottimo modo per fare segnalazioni, ma come sei riuscito Max a far comparire il tag 1con il link alla relativa discussione nel commento del commit?

**Comment by mlgdominici** [comment]
La questione ha perso un po' la sua ragion d'essere, perché ora ciascun articolo è compilato separatamente, quindi ogni ridefinizione è per forza di cose locale.
